version: '3'

services:
  server:
    container_name: trust4ai-bias-generator-llm
    image: trust4ai-bias-generator-llm:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    env_file:
      - .env
    networks:
      - trust4ai-bias-generator-llm-network

networks:
  trust4ai-bias-generator-llm-network:
    driver: bridge