version: '3'

services:
  server:
    container_name: muse
    image: muse:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    env_file:
      - .env
    networks:
      - muse-network

networks:
  muse-network:
    driver: bridge